### ISSUE TITLE
July 11th Project Progress

### ISSUE THREAD

**Issue by sylvstrc** [anneguo3/budget-buddy#25]

**Comment by sylvstrc** [comment]
h2i1b:

1. I worked on Integrated Google Oauth with our app as well as creating the backend users route for put/get requests for creating and retrieving data for the respective user (with their associated google id).
2. In the next sprint I will work on integrating the current user into the redux reducer so that all api calls will pertain to that user's data. I will also work on revamping the login page and changing the behaviour of the app to only allow accessing specific pages after logging in.
3. I struggled this week with learning about Oauth as it was a completely new topic to me.

**Comment by elaineay** [comment]
c6f1b:
1. I worked on the overview page. Here I refactored and expanded the aggregate reducer functionality to populate after our initial get calls to the database, as well as decrementing as items were deleted. I then worked on passing in these values into props and their respective components as needed. 
2. This sprint I will:
- Create reducers to a) sort transactions into their respective categories and b) timebox transactions
- Hook up the reducers to the appropriate data visuals
- I will also continue to investigate the issue in (3)
3. I struggled with figuring out where to make calls to initialize the aggregate reducer and will continue to investigate this issue as we continue on the next sprint. Since we were doing a get call every time we were rendering the component, the aggregate reducer was being populated too many times and would sum itself again every time the component rendered.

**Comment by anneguo3** [comment]
l4j1b:
1. I created the ability to add categories to each entry, along with the categories being dynamically shown based on the user's selection of either an Income or Expense item, along with supporting my teammate with the Aggregation Reducer
2. Over the next two weeks, I plan on adding functionality to allow users to filter their transactions by month within the data view page along with the ability specify the month that is displayed within the overview page. I will also be working on creating a user page where individuals have the ability to customize their categories.
3. I struggled with getting to have the categories customize based on a prior user input, and tried a variety of things, and in turn over-complicated the issue, such as creating a reducer, however in reflecting on the actual problem statement I realized the issue could be easily addressed by using state.

**Comment by ansel-rangers11** [comment]
o8c1b:
1. Refactored overhaul the project from using the unscalable redux toolkit to a more standard redux thunk and react-redux set up. Also built the backend Express app as well as the required APIs for our transactions as well as the basic filtering mechanism for Income vs Expenses transactions using redux. 
2. Complete the initMongo intialization script so that we can input mock data into our database for easy setup and teardown. Abstracting out the password for our app is also necessary work I will tackle on for increased data integrity and confidentiality. 
3. Tearing down the redux toolkit and building up our app without it proved to be quite the undertaking but it was completed with no side effects.
