### ISSUE TITLE
July 25th: Project Progress

### ISSUE THREAD

**Issue by ansel-rangers11** [anneguo3/budget-buddy#37]
July 25th: Project Progress

**Comment by elaineay** [comment]
c6f1b:

This week I worked on: debugging the reducer for aggregation of entries (income/expense), creating a categories reducer, hooking up the transactions with their respective reducers and the visual components

Next week: continue debugging the reducers for the respective visual components with the ability to create new categories as users add them, create timeboxing functionality for visual components and the reducer storing the timeboxed transactions

Obstacles: Figuring out how/where to initialize the reducers for the data visuals since they are contingent on the initial GET call for the transactions. There was also a difference of how the data was stored after merging with my partners' respective work, which affected the way the data was displayed, and subsequently shown in the visuals. These discrepancies are being looked into for the next sprint.

**Comment by ansel-rangers11** [comment]
o8c1b:

This week I worked on: creating mock data for our data as well as facilitating deployment to Heroku. I also abstracted out the password for our DB to enforce security reasons.

Next week: I will be tackling a bug for re-rendering of our list of transactions when adding or deleting. I will also investigate feasibility of having a loading page when axios calls are being made and see if they fail or succeed. I will also be updating the favicon and tab name. 

Obstacles: I ran into difficulty in deploying to heroku because we have hardcoded some values into our code which needed to be re-pointed. I also ran into trouble in helping some deployment bugs as we shifted away from localhost to deployed Heroku of which I assisted my friends with. Some of the errors silently fail and hard to detect. Definitely challenged my debugging skills.

**Comment by sylvstrc** [comment]
h2i1b:

I worked on adding user information to reducer store upon login, changing backend endpoints to accept userID as a parameter to make requests user specific + changing respective frontend calls, and reconfiguring the routing to restrict access of pages to logged in users as well as redirects upon login/logout.

Next sprint I will be debugging the 'tangled' get requests, adding category functionality to the backend with GET/POST requests + hooking that up to the Frontend, and revising the structure of the database. 

We encountered great difficulties after deployment with the hardcoded values, figuring out how to enable google oauth with different domains and a lot with intergration of our reducers as it introduced new bugs.

**Comment by anneguo3** [comment]
l4j1b:

Over the last two weeks, I worked on creating the UI of the profile page, allowing users to put in custom categories for both their expense and income categories. I also worked on augmenting the filtering capability for our entries, by allowing the user to filter based on month and year on top of the existing expense and income category filtering.

Next sprint, I will be working on getting the same month filtering ability to work for the overview data page and also working on the ability for the user to upload an xlsx file that will be parsed which is easier to mass upload data by the user. 

I really struggled initially with the added ability to filter all our entries by month and year on top of the income/expense filter due to clashing actions and mixing of the order of operations, in talking to a team member I realized that the proper way to approach the problem was to actually abstract out all the filters into one action and based on the payload adjust the filtered entries.
